### ISSUE TITLE
(HWS) Siti governativi americani bloccati

### ISSUE THREAD

**Issue by Bertaz** [gioxx/xfiles#11]
Il commit 6a19c8fc8514d ha aggiunto praticamente tutti i siti governativi americani senza apparente motivo.
Il readme dice che HWS si basa su MalwareDomainList e ZeusTracker. ZeusTracker è discontinued da luglio 2019 e in MDL non sono presenti questi siti.

Per quale motivo sono stati aggiunti o da quale altra lista sono stati importati?

**Comment by Bertaz** [comment]
Inoltre il commit successivo 9206a7745a0d1d7633c2 ha rimosso un sacco di siti ancora online che, a una rapida occhiata, sembrano da bloccare. Come 7zip.it e adblock.fr

**Comment by rfc1459** [comment]
Riesumo la issue perché ho sbattuto contro `nasa.gov` bloccato da HWS e ne ho approfittato per guardare cosa c'è nella blocklist originale (https://github.com/tigthor/NSA-CIA-Blocklist/blob/main/HOSTS/HOSTS).

C'è veramente troppa, troppa roba che fatico a definire "mass surveillance". Giusto per citare i casi più eclatanti:

* `whitehouse.gov`
* `congress.gov`
* `senate.gov`
* `federalreserve.gov`
* `nasa.gov` (appunto)
* `matematica.univaq.it` (... e mo' che c'entra il corso di laurea in Matematica dell'Università degli Studi dell'Aquila con NSA e CIA?!?!?)
* diversi DNS server e mailserver di vari provider (tra cui TIM e Fastweb) ed università italiane

Io sinceramente rivaluterei l'opportunità di usare una fonte del genere :)

**Comment by gioxx** [comment]
Ciao Teo, la richiesta ha senso e al momento ho disattivato l'importazione di quella lista all'interno di HWS/UPD. Potrei approfittare di qualche giorno libero per dare un'occhiata più approfondita e provare a salvare qualcosa, lasciando fuori ciò che c'è di più eclatante e che difficilmente porta problemi all'utente finale, così da poter reimportare in parte il contenuto della lista in futuro.
Intanto grazie :)

**Comment by gioxx** [comment]
Ho reintegrato parte di quella lista dopo averla ripulita, in pratica ho accolto le richieste di @Bertaz e rivisto il tutto come mi segnalavi tu @rfc1459.
La lista "pulita" è quella disponibile qui: https://github.com/gfscom/NSA-CIA-Blocklist/blob/main/HOSTS/HOSTS
