### ISSUE TITLE
doi.org bloccato

### ISSUE THREAD

**Issue by gdv** [gioxx/xfiles#15]
Grazie per il lavoro fatto per questa risorsa preziosa.

Ho notato che il dominio `doi.org` è bloccato, anche se è nella whitelist di mitchellkrogza

Più in generale, vorrei sapere se sei interessato ad una pull request che aggiunga la gestione della suddetta whitelist (modificando https://github.com/gioxx/xfiles/blob/master/sh/make_upd.sh in modo che il tutto sia automatizzato).

Grazie

**Comment by gioxx** [comment]
Ciao @gdv, assolutamente volentieri! :-)
Considera che è già previsto un sistema di pulizia (vedi https://github.com/gioxx/xfiles/blob/ad8a288a8ad01e19555a8b9ed05f2797c3ae96c5/sh/make_upd.sh#L19) che si basa sulla lista esclusioni https://github.com/gioxx/xfiles/blob/master/contrib/upd_exclude (al suo interno ci sono proprio quei domini da ripulire dalla lista UPD/HWS).

Sentiti libero di proporre la tua modifica o semplicemente basarti su questo meccanismo già funzionante per portare dentro anche la whitelist di mitchellkrogza ;-)

**Comment by gioxx** [comment]
Mandato la modifica in merge @gdv, grazie mille per il contributo! :-)
Nel frattempo ho anche aggiornato lo script "gemello" lato Raspberry che si occupa dei rilasci CRON non gestiti da GitHub.

**Comment by gdv** [comment]
Non ho capito come generi l'intestazione (cioè le prime righe) del file `upd.txt`. Di conseguenza non sono riuscito a fare un test adeguato (ho visto in una commit che avevo ancora un typo in un nome di file).
Mi sembra che `whitelist.txt` continui a crescere, perchè c'è `>>` invece di `>`, ma senza un test preferisco evitare modifiche.

Grazie ancora del tuo lavoro

**Comment by gioxx** [comment]
Rieccomi @gdv, avevo visto quel problema e l'ho corretto successivamente con un altro commit separando le strade (in pratica la upd_exclude rimane "ferma" ai contributi miei e degli utenti mentre la whitelist viene integrata a parte, con un file che poi viene cancellato al termine del processo).
Le informazioni di cui tu parli si trovano nell'Action: https://github.com/gioxx/xfiles/blob/master/.github/workflows/make_upd.yml
