### ISSUE TITLE
No Ads X File - errori in uBlock Origin

### ISSUE THREAD

**Issue by SampeiNihira** [gioxx/xfiles#19]
Ciao Gioxx ,dall'immagine sotto potresti verificare e correggere i 16 errori che uBlock Origin notifica agli utenti con l'utilizzo della tua lista:

![1](https://github.com/gioxx/xfiles/assets/44166263/ff35359f-38b0-4df4-aa11-1fd88dcf0811)

Puoi verificare da solo che Easy List Italy (minified) con più regole ha solo 1 errore.

Grazie.

**Comment by gioxx** [comment]
C'erano un paio di filtri "in errore" secondo uBlock ma perfettamente funzionanti con AdBlock Plus. Detto ciò, ho comunque risolto perché ne ho approfittato per tagliare qualcosa di non più necessario.
Le modifiche fanno parte di questi commit: https://github.com/gioxx/xfiles/commit/2c97b93735f5da3b6c95bd46c803769bb60b25f1 e https://github.com/gioxx/xfiles/commit/1a9c98acacebf3c5ddb3847d2a875f7cb65c75fc.

La lista sperimentale è già aggiornata, quella stabile verrà allineata tra qualche giorno in maniera automatica. Il problema non è così impattante da non renderla funzionante 😄 👍 

Intanto grazie per la segnalazione.
