### ISSUE TITLE
Chiedere di aggiungere X Files Stable di default in uBlock Origin

### ISSUE THREAD

**Issue by marcoclg19** [gioxx/xfiles#20]
Ciao,
ho visto che AdGuard ha inserito già da molto tempo la tua [lista](https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt) tra le quelle selezionabili. 
Secondo te, si potrebbe chiedere allo sviluppatore di uBlock Origin di inserirla anche lui nelle liste regionali per la lingua italiana assieme a EasyList Italy? Sempre se sei d'accordo, la mia è solo una idea!
La tua lista è veramente ottima che secondo me sarebbe ideale se fosse già presente in uBlock e di conseguenza anche nella versione MV3.

**Comment by gioxx** [comment]
Ciao @marcoclg19.
In realtà X Files faceva parte delle liste regionali di uBlock fino a quando hanno deciso di fare pulizia e mantenere solo le EasyList come discusso all'interno di una vecchia issue qui: https://github.com/uBlockOrigin/uAssets/issues/11204

In tutta onestà, nonostante io continui a sponsorizzare l'uso di uBlock (lo uso io per primo), sono ancora scocciato da quanto fatto perché la lista in Italia è molto usato e non ha - ancora oggi - nessun senso l'averla esclusa dall'elenco delle disponibili.

Detto ciò, di certo non tornerò a chiedere di reinserirla visto che il "tribunale" ha già sentenziato all'epoca. Continuerò a mantenerla finché ne avrò le forze e la voglia, tu potrai scegliere di utilizzarla sul componente aggiuntivo che più ti piace :-)
