### ISSUE TITLE
The rule "ads.*/$from=..." breaks (the loading of the stylesheet on) etsy

### ISSUE THREAD

**Issue by DrReD** [gioxx/xfiles#23]
The complete rule is:
==============
ads.*/$from=~docs.yahoo.com|~finance.yahoo.com|~mail.yahoo.com|~mediaset.it|~reachadv.it|~teleradiopadrepio.it|~tzetze.it

The URL wrongly blocked is:
==================
https://www.etsy.com/dac/search2_neu/desktop.5b4fb8ec10b640,web-toolkit-v2/modules/action_groups/action_groups.f60a9d0a446dd9,listings/listing-card-animation.c31d0f644a0398,__modules__Registry__src__/Common/RegistryIngressBanner/View.f60a9d0a446dd9,search2_neu/modules/search_ingress.f60a9d0a446dd9,search2_neu/modules/narrow_by_theme.f60a9d0a446dd9,web-toolkit-v2/modules/panels/panels.f60a9d0a446dd9,/neu/common/refine-by-listing-header.f60a9d0a446dd9,market/search_results.f60a9d0a446dd9,search2_neu/modules/collage_listing_card.f60a9d0a446dd9,neu/modules/favorite_button_defaults.f60a9d0a446dd9,listings/listing-card-video.f60a9d0a446dd9,common/listing_card_text_badge.b1c6bd381ce780,common/stars-sprite.b1c6bd381ce780,neu/modules/listing_card_signals.19366a52442557,search2_neu/skeletons.f60a9d0a446dd9,search2_neu/modules/common/pagination.1b0ed389f477ba,recommendations/card_group.f60a9d0a446dd9,search2_neu/modules/common/result_info_including_ads.2ec02d4eb6d23b,neu/common/responsive_listing_grid.f60a9d0a446dd9,web-toolkit-v2/modules/forms/checkboxes.f60a9d0a446dd9,web-toolkit-v2/modules/forms/form_groups.f60a9d0a446dd9,web-toolkit-v2/modules/forms/radios.f60a9d0a446dd9,search2_neu/filter/filter-toolkit-v2.f60a9d0a446dd9,search2_neu/filter/desktop-overlay.f60a9d0a446dd9,favorites/collection/list.f60a9d0a446dd9,favorites/collection/row.f60a9d0a446dd9,favorites/adaptive-height-desktop.f60a9d0a446dd9.css?variant=sasquatch&features=minl%3Aon%2Cmino%3Aoff&v=3

Here is a quick and dirty workaround:
========================
@@||www.etsy.com/dac/search2_neu/$stylesheet,domain=www.etsy.com

**Comment by gioxx** [comment]
Ciao @DrReD e grazie per la segnalazione. Carico il fix che hai suggerito nella lista esclusioni, al momento solo nella lista non stabile, passerà automaticamente a quella stabile entro una manciata di giorni.
