### ISSUE TITLE
Ad server: cintnetworks.com

### ISSUE THREAD

**Issue by davidhedlund** [gioxx/xfiles#5]
This filter will block the cintnetworks.com ad server:

> ||cintnetworks.com^$third-party

**Comment by gioxx** [comment]
Hi David! I don't know this ad server, do You think is necessary for an italian filter list?
Thanks :-)

**Comment by davidhedlund** [comment]
Not necessarily but Italy tops the traffic - https://www.alexa.com/siteinfo/cintnetworks.com

**Comment by gioxx** [comment]
Available from now, thanks for the contributing.

**Comment by davidhedlund** [comment]
Thank you for all you contributions.
