### ISSUE TITLE
License for the filter list

### ISSUE THREAD

**Issue by fmarier** [gioxx/xfiles#7]
I noticed that this list and repository don't have a LICENSE file.

What license is the list under? Is it the standard EasyList license? https://easylist.to/pages/licence.html

**Comment by gioxx** [comment]
Ciao Francois, no, X Files use a CC License: https://github.com/gioxx/xfiles#licenza-duso-distribuzione-e-supporto

**Comment by fmarier** [comment]
I see that you also added a `LICENSE` file in https://github.com/gioxx/xfiles/commit/cf953055fc09243185365e3a5fe2ae7a7456ce17.

Thanks!
